### ISSUE TITLE
Inaccurate bot data 

### ISSUE THREAD

**Issue by summermielke** [x-tools/xtools-legacy#116]
https://tools.wmflabs.org/xtools-articleinfo/?article=Epidemia+de+%C3%A9bola+de+2014-2016&project=es.wikipedia.org

On this page xtools reports 54 edits done by bots. I scraped the data myself (for academic research) and there are only 34 edits. The number of total edits is correct. Xtools is counting some non-bot users as bots and also double counting their edits. Taichi and Savh are not bots and only did half as many edits as what is reported here.

The page titled Tour de Francia 2012 on es.wikipedia.org (I can't post a link because it is not coming up right now, it was working yesterday...) reports 8 bot edits. There are actually 27 bot edits. The total edits is correct. This time the problem is the opposite of the Ebola page. Here there are bot accounts that xtools did not count as bots. 
I noticed a bot account (Ptbotgourou) is NOT counted as a bot on the Tour de Francia 2012 ES page, but IS counted as bots on the Tour de France 2012 German (de) page. Could this indicate that the problem is the Spanish Wikipedia site, not xtools?

**Comment by summermielke** [comment]
https://tools.wmflabs.org/xtools-articleinfo/?article=Vladimir+Poutine&project=fr.wikipedia.org

This page also has errors. There are more like 262 bot edits, not 135.

**Comment by Matthewrbowker** [comment]
@summermielke Where are you getting numbers "like 262?"

**Comment by summermielke** [comment]
I scraped the data, exported it to an excel sheet, and did a VLOOKUP. I'd be happy to send them if you want to see. But the errors are apparent on x tools. On Vladimir Poutine for instance there is a bot called YurikBot that is listed in users but not in bots. It is not counted toward the bot edit percentage.

**Comment by Matthewrbowker** [comment]
Huh.  According to https://github.com/x-tools/xtools/blob/caa7162/modules/ArticleInfo.php#L1152-L1166 , the bots are generated based on the flags.  According to the SUL info, https://meta.wikimedia.org/w/index.php?title=Special%3ACentralAuth&target=YurikBot does not have a bot flag on either the french wiki or the spanish wiki.

**Comment by summermielke** [comment]
Oh, I see. What about the user Taichi on the first link I posted? Why is a nonbot being counted as a bot?

**Comment by MusikAnimal** [comment]
Looks like they used to be a bot https://es.wikipedia.org/w/index.php?title=Especial:Registro&user=&page=User%3ATaichi&type=rights

I am working on a fix for the new version of XTools, and will try to fix the current version as well

**Comment by MusikAnimal** [comment]
Actually, I think this is just bad data. I noticed this with another project I was working on, where apparently the replicas sometimes aren't up-to-date, maybe that's what has happened here. It seems the `user_groups` table does not hold historical data, so it should not be reporting Taichi as a bot.

**Comment by MusikAnimal** [comment]
Scratch that, it's not bad data. The issue is bot edits do get flagged as such, but only in `recentchanges`, not in `revision` or via another table that is not regularly purged. So, the only way I can think of to assert it was a bot edit is to cross-reference when the user right was added/removed via the `logging` table with the timestamps in the revision history. This would slow things down tremendously. We could fix this particular issue with User:Taichi by not checking `user_former_groups`, but then we wouldn't be checking for legitimate bots who are no longer flagged. That said I'm proposing we close this as a WONTFIX as it seems to be an edge case.

**Comment by MusikAnimal** [comment]
What we can do is indicate if the user is a _former bot_, that should hopefully alleviate some confusion. It seems many human accounts are given the bot flag on eswiki, so not really an edge case for them when it would be for many other wikis

**Comment by summermielke** [comment]
> but then we wouldn't be checking for legitimate bots who are no longer flagged

Forgive my ignorance... but why would a legitimate bot that has been flagged at some point in time no longer be flagged? 

I did not realize that there are human accounts that were previously bot accounts. Thanks for letting me know and looking into this.

**Comment by MusikAnimal** [comment]
> Forgive my ignorance... but why would a legitimate bot that has been flagged at some point in time no longer be flagged?

Often advanced user rights are removed if the user is inactive, primarily for security reasons.

I've made the new articleinfo tool show if they were previously a bot, which I think is the best option. Let's say we went with the more complicated solution where we cross-reference the user rights log, as I described above... even then you may have human editors showing up as bots on XTools. Unfortunately there's nothing we can do.

The issue lies with this malpractice on eswiki. For instance, User:Taichi [added the bot flag](https://es.wikipedia.org/w/index.php?title=Especial:Registro&action=view&page=User%3ATaichi&type=rights&offset=20170228000000&limit=2) to their account for "mass rollback of spam". [Sysops already have rollback](https://es.wikipedia.org/wiki/Especial:ListaDerechosGrupos#sysop) and can also mark rolled-back edits as bot edits (`markbotedits`), so there's no reason to add the bot flag. If they really wanted "be treated as an automated process" (`bot` permission) they could add themselves to the [flood user group](https://es.wikipedia.org/wiki/Especial:ListaDerechosGrupos#flood), which appears to be  documented at [Wikipedia:Pseudobots](https://es.wikipedia.org/wiki/Wikipedia:Pseudobots).

**Comment by Matthewrbowker** [comment]
@MusikAnimal Has this been fixed in the new XTools?  Or at least addressed?  The way I read it, most of the issue is in procedure not in XTools parsing of data.

**Comment by MusikAnimal** [comment]
Yes, the edits by these accounts still show in the "Top 10 by added text", etc., so the only potential confusion is that a human account may show up in the bot list. If that is the case it will say "former bot". This isn't that bad, in my opinion. I still put fault at eswiki practice, as human accounts should not be bots – ever. We could use the timestamps of when the user rights changed to find out which edits were made when the account had the bot flag, but I think that's unnecessarily complex for what seems like an edge case.
